[2024-04-01T04:49:10.305+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deploy_project_kafkaClickhouse.task_1_runConsumer manual__2024-04-01T04:49:09.160460+00:00 [queued]>
[2024-04-01T04:49:10.312+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deploy_project_kafkaClickhouse.task_1_runConsumer manual__2024-04-01T04:49:09.160460+00:00 [queued]>
[2024-04-01T04:49:10.312+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-04-01T04:49:10.322+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task_1_runConsumer> on 2024-04-01 04:49:09.160460+00:00
[2024-04-01T04:49:10.328+0000] {standard_task_runner.py:57} INFO - Started process 768 to run task
[2024-04-01T04:49:10.330+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'deploy_project_kafkaClickhouse', 'task_1_runConsumer', 'manual__2024-04-01T04:49:09.160460+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/executeClickhouse.py', '--cfg-path', '/tmp/tmpf7gx2qy5']
[2024-04-01T04:49:10.331+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask task_1_runConsumer
[2024-04-01T04:49:10.366+0000] {task_command.py:415} INFO - Running <TaskInstance: deploy_project_kafkaClickhouse.task_1_runConsumer manual__2024-04-01T04:49:09.160460+00:00 [running]> on host 977df1ccf323
[2024-04-01T04:49:10.422+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deploy_project_kafkaClickhouse' AIRFLOW_CTX_TASK_ID='task_1_runConsumer' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T04:49:09.160460+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-01T04:49:09.160460+00:00'
[2024-04-01T04:49:10.422+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T04:49:10.423+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/clickhouse/consumer.py']
[2024-04-01T04:49:10.434+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T04:49:10.536+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-04-01T04:49:10.536+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/clickhouse/consumer.py", line 2, in <module>
[2024-04-01T04:49:10.537+0000] {subprocess.py:93} INFO -     from clickhouse_driver import Client
[2024-04-01T04:49:10.537+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'clickhouse_driver'
[2024-04-01T04:49:10.539+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-01T04:49:10.550+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-01T04:49:10.552+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=deploy_project_kafkaClickhouse, task_id=task_1_runConsumer, execution_date=20240401T044909, start_date=20240401T044910, end_date=20240401T044910
[2024-04-01T04:49:10.563+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task task_1_runConsumer (Bash command failed. The command returned a non-zero exit code 1.; 768)
[2024-04-01T04:49:10.582+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-04-01T04:49:10.600+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
