[2024-04-01T08:32:47.276+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deploy_project_kafkaClickhouse.task_Clickhouse_Consumer scheduled__2024-03-30T09:30:00+00:00 [queued]>
[2024-04-01T08:32:47.293+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deploy_project_kafkaClickhouse.task_Clickhouse_Consumer scheduled__2024-03-30T09:30:00+00:00 [queued]>
[2024-04-01T08:32:47.293+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-04-01T08:32:47.309+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task_Clickhouse_Consumer> on 2024-03-30 09:30:00+00:00
[2024-04-01T08:32:47.315+0000] {standard_task_runner.py:57} INFO - Started process 1077 to run task
[2024-04-01T08:32:47.318+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'deploy_project_kafkaClickhouse', 'task_Clickhouse_Consumer', 'scheduled__2024-03-30T09:30:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/executeClickhouse.py', '--cfg-path', '/tmp/tmph669i56p']
[2024-04-01T08:32:47.319+0000] {standard_task_runner.py:85} INFO - Job 45: Subtask task_Clickhouse_Consumer
[2024-04-01T08:32:47.364+0000] {task_command.py:415} INFO - Running <TaskInstance: deploy_project_kafkaClickhouse.task_Clickhouse_Consumer scheduled__2024-03-30T09:30:00+00:00 [running]> on host 977df1ccf323
[2024-04-01T08:32:47.437+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deploy_project_kafkaClickhouse' AIRFLOW_CTX_TASK_ID='task_Clickhouse_Consumer' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T09:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-30T09:30:00+00:00'
[2024-04-01T08:32:47.439+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T08:32:47.440+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/clickhouse/consumer.py']
[2024-04-01T08:32:47.457+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T08:35:26.693+0000] {subprocess.py:93} INFO - Subscribed to Kafka topic: log_data
[2024-04-01T08:35:26.694+0000] {subprocess.py:93} INFO - 
[2024-04-01T08:35:26.694+0000] {subprocess.py:93} INFO - inserting data into ClickHouse...
[2024-04-01T08:35:26.694+0000] {subprocess.py:93} INFO - 
[2024-04-01T08:35:26.695+0000] {subprocess.py:93} INFO - done
[2024-04-01T08:35:26.695+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-04-01T08:35:26.695+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/clickhouse/consumer.py", line 97, in <module>
[2024-04-01T08:35:26.695+0000] {subprocess.py:93} INFO -     print('done')
[2024-04-01T08:35:26.695+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/clickhouse/consumer.py", line 86, in main
[2024-04-01T08:35:26.695+0000] {subprocess.py:93} INFO - 
[2024-04-01T08:35:26.695+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 382, in execute
[2024-04-01T08:35:26.695+0000] {subprocess.py:93} INFO -     rv = self.process_ordinary_query(
[2024-04-01T08:35:26.695+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 580, in process_ordinary_query
[2024-04-01T08:35:26.696+0000] {subprocess.py:93} INFO -     return self.receive_result(with_column_types=with_column_types,
[2024-04-01T08:35:26.696+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 213, in receive_result
[2024-04-01T08:35:26.696+0000] {subprocess.py:93} INFO -     return result.get_result()
[2024-04-01T08:35:26.696+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/result.py", line 50, in get_result
[2024-04-01T08:35:26.696+0000] {subprocess.py:93} INFO -     for packet in self.packet_generator:
[2024-04-01T08:35:26.696+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 229, in packet_generator
[2024-04-01T08:35:26.696+0000] {subprocess.py:93} INFO -     packet = self.receive_packet()
[2024-04-01T08:35:26.696+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 246, in receive_packet
[2024-04-01T08:35:26.696+0000] {subprocess.py:93} INFO -     raise packet.exception
[2024-04-01T08:35:26.696+0000] {subprocess.py:93} INFO - clickhouse_driver.errors.ServerException: Code: 60.
[2024-04-01T08:35:26.696+0000] {subprocess.py:93} INFO - DB::Exception: Table default.logs doesn't exist. Stack trace:
[2024-04-01T08:35:26.697+0000] {subprocess.py:93} INFO - 
[2024-04-01T08:35:26.697+0000] {subprocess.py:93} INFO - 0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /usr/bin/clickhouse
[2024-04-01T08:35:26.697+0000] {subprocess.py:93} INFO - 1. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0xa89b823 in /usr/bin/clickhouse
[2024-04-01T08:35:26.697+0000] {subprocess.py:93} INFO - 2. void std::__1::__optional_storage_base<DB::Exception, false>::__construct<int const&, char const (&) [23], std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int const&, char const (&) [23], std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0x1352ac0f in /usr/bin/clickhouse
[2024-04-01T08:35:26.697+0000] {subprocess.py:93} INFO - 3. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>, std::__1::optional<DB::Exception>*) const @ 0x13519082 in /usr/bin/clickhouse
[2024-04-01T08:35:26.697+0000] {subprocess.py:93} INFO - 4. DB::DatabaseCatalog::getTable(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>) const @ 0x1352126b in /usr/bin/clickhouse
[2024-04-01T08:35:26.697+0000] {subprocess.py:93} INFO - 5. DB::InterpreterInsertQuery::getTable(DB::ASTInsertQuery&) @ 0x13a49ab0 in /usr/bin/clickhouse
[2024-04-01T08:35:26.697+0000] {subprocess.py:93} INFO - 6. DB::InterpreterInsertQuery::execute() @ 0x13a4b7a9 in /usr/bin/clickhouse
[2024-04-01T08:35:26.697+0000] {subprocess.py:93} INFO - 7. ? @ 0x13d1434c in /usr/bin/clickhouse
[2024-04-01T08:35:26.697+0000] {subprocess.py:93} INFO - 8. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13d11e55 in /usr/bin/clickhouse
[2024-04-01T08:35:26.697+0000] {subprocess.py:93} INFO - 9. DB::TCPHandler::runImpl() @ 0x147f050f in /usr/bin/clickhouse
[2024-04-01T08:35:26.698+0000] {subprocess.py:93} INFO - 10. DB::TCPHandler::run() @ 0x14804259 in /usr/bin/clickhouse
[2024-04-01T08:35:26.698+0000] {subprocess.py:93} INFO - 11. Poco::Net::TCPServerConnection::start() @ 0x1745e52f in /usr/bin/clickhouse
[2024-04-01T08:35:26.698+0000] {subprocess.py:93} INFO - 12. Poco::Net::TCPServerDispatcher::run() @ 0x17460981 in /usr/bin/clickhouse
[2024-04-01T08:35:26.698+0000] {subprocess.py:93} INFO - 13. Poco::PooledThread::run() @ 0x17611609 in /usr/bin/clickhouse
[2024-04-01T08:35:26.698+0000] {subprocess.py:93} INFO - 14. Poco::ThreadImpl::runnableEntry(void*) @ 0x1760ed00 in /usr/bin/clickhouse
[2024-04-01T08:35:26.699+0000] {subprocess.py:93} INFO - 15. ? @ 0x7f5a9c959609 in ?
[2024-04-01T08:35:26.700+0000] {subprocess.py:93} INFO - 16. __clone @ 0x7f5a9c880293 in ?
[2024-04-01T08:35:26.700+0000] {subprocess.py:93} INFO - 
[2024-04-01T08:35:26.721+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-01T08:35:26.734+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-01T08:35:26.737+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=deploy_project_kafkaClickhouse, task_id=task_Clickhouse_Consumer, execution_date=20240330T093000, start_date=20240401T083247, end_date=20240401T083526
[2024-04-01T08:35:26.748+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 45 for task task_Clickhouse_Consumer (Bash command failed. The command returned a non-zero exit code 1.; 1077)
[2024-04-01T08:35:26.791+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-04-01T08:35:26.805+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-01T08:38:48.809+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deploy_project_kafkaClickhouse.task_Clickhouse_Consumer scheduled__2024-03-30T09:30:00+00:00 [queued]>
[2024-04-01T08:38:48.816+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deploy_project_kafkaClickhouse.task_Clickhouse_Consumer scheduled__2024-03-30T09:30:00+00:00 [queued]>
[2024-04-01T08:38:48.816+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-04-01T08:38:48.826+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task_Clickhouse_Consumer> on 2024-03-30 09:30:00+00:00
[2024-04-01T08:38:48.830+0000] {standard_task_runner.py:57} INFO - Started process 1288 to run task
[2024-04-01T08:38:48.833+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'deploy_project_kafkaClickhouse', 'task_Clickhouse_Consumer', 'scheduled__2024-03-30T09:30:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/executeClickhouse.py', '--cfg-path', '/tmp/tmpqbeecjlt']
[2024-04-01T08:38:48.834+0000] {standard_task_runner.py:85} INFO - Job 51: Subtask task_Clickhouse_Consumer
[2024-04-01T08:38:48.870+0000] {task_command.py:415} INFO - Running <TaskInstance: deploy_project_kafkaClickhouse.task_Clickhouse_Consumer scheduled__2024-03-30T09:30:00+00:00 [running]> on host 977df1ccf323
[2024-04-01T08:38:48.953+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deploy_project_kafkaClickhouse' AIRFLOW_CTX_TASK_ID='task_Clickhouse_Consumer' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T09:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-30T09:30:00+00:00'
[2024-04-01T08:38:48.954+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T08:38:48.954+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/clickhouse/consumer.py']
[2024-04-01T08:38:48.965+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T09:09:22.224+0000] {subprocess.py:93} INFO - %5|1711962562.224|PARTCNT|rdkafka#consumer-1| [thrd:main]: Topic log_data partition count changed from 1 to 0
[2024-04-01T09:10:03.390+0000] {subprocess.py:93} INFO - %4|1711962603.390|OFFSET|rdkafka#consumer-1| [thrd:main]: log_data [0]: offset reset (at offset 150 (leader epoch 0), broker 1) to offset BEGINNING (leader epoch -1): fetch failed due to requested offset not available on the broker: Broker: Offset out of range
[2024-04-01T09:10:03.900+0000] {subprocess.py:93} INFO - WARNING:clickhouse_driver.connection:Error on 172.18.0.1:9000 ping: Unexpected EOF while reading bytes
[2024-04-01T09:10:03.900+0000] {subprocess.py:93} INFO - WARNING:clickhouse_driver.connection:Connection was closed, reconnecting.
[2024-04-01T09:10:03.900+0000] {subprocess.py:93} INFO - WARNING:clickhouse_driver.connection:Error on socket shutdown: [Errno 107] Transport endpoint is not connected
[2024-04-01T09:10:03.901+0000] {subprocess.py:93} INFO - WARNING:clickhouse_driver.connection:Failed to connect to 172.18.0.1:9000
[2024-04-01T09:10:03.901+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-04-01T09:10:03.901+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 396, in connect
[2024-04-01T09:10:03.901+0000] {subprocess.py:93} INFO -     return self._init_connection(host, port)
[2024-04-01T09:10:03.901+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 326, in _init_connection
[2024-04-01T09:10:03.901+0000] {subprocess.py:93} INFO -     self.socket = self._create_socket(host, port)
[2024-04-01T09:10:03.901+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 297, in _create_socket
[2024-04-01T09:10:03.902+0000] {subprocess.py:93} INFO -     raise err
[2024-04-01T09:10:03.902+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 288, in _create_socket
[2024-04-01T09:10:03.902+0000] {subprocess.py:93} INFO -     sock.connect(sa)
[2024-04-01T09:10:03.902+0000] {subprocess.py:93} INFO - ConnectionRefusedError: [Errno 111] Connection refused
[2024-04-01T09:10:03.904+0000] {subprocess.py:93} INFO - Consumer started
[2024-04-01T09:10:03.905+0000] {subprocess.py:93} INFO - Subscribed to Kafka topic: log_data
[2024-04-01T09:10:03.905+0000] {subprocess.py:93} INFO - 
[2024-04-01T09:10:03.905+0000] {subprocess.py:93} INFO - inserting data into ClickHouse...
[2024-04-01T09:10:03.905+0000] {subprocess.py:93} INFO - 
[2024-04-01T09:10:03.905+0000] {subprocess.py:93} INFO - Inserted data into ClickHouse: ('2024-03-25 08:30:00', 12345, 'click', 'ad123', 'campaign_xyz', 'Google Ads')
[2024-04-01T09:10:03.905+0000] {subprocess.py:93} INFO - Inserted data into ClickHouse: ('2024-03-25 09:15:00', 54321, 'view', 'ad456', 'campaign_abc', 'Facebook Ads')
[2024-04-01T09:10:03.905+0000] {subprocess.py:93} INFO - Inserted data into ClickHouse: ('2024-03-25 10:00:00', 67890, 'click', 'ad789', 'campaign_def', 'Twitter Ads')
[2024-04-01T09:10:03.905+0000] {subprocess.py:93} INFO - Inserted data into ClickHouse: ('2024-03-25 10:30:00', 23456, 'click', 'ad234', 'campaign_xyz', 'Google Ads')
[2024-04-01T09:10:03.905+0000] {subprocess.py:93} INFO - Inserted data into ClickHouse: ('2024-03-25 11:45:00', 67890, 'view', 'ad789', 'campaign_def', 'Twitter Ads')
[2024-04-01T09:10:03.905+0000] {subprocess.py:93} INFO - Inserted data into ClickHouse: ('2024-03-25 12:15:00', 12345, 'click', 'ad123', 'campaign_xyz', 'Google Ads')
[2024-04-01T09:10:03.906+0000] {subprocess.py:93} INFO - Inserted data into ClickHouse: ('2024-03-25 13:00:00', 54321, 'view', 'ad456', 'campaign_abc', 'Facebook Ads')
[2024-04-01T09:10:03.906+0000] {subprocess.py:93} INFO - Inserted data into ClickHouse: ('2024-03-25 14:30:00', 23456, 'click', 'ad234', 'campaign_xyz', 'Google Ads')
[2024-04-01T09:10:03.906+0000] {subprocess.py:93} INFO - Inserted data into ClickHouse: ('2024-03-25 15:45:00', 67890, 'view', 'ad789', 'campaign_def', 'Twitter Ads')
[2024-04-01T09:10:03.906+0000] {subprocess.py:93} INFO - Inserted data into ClickHouse: ('2024-03-25 16:15:00', 12345, 'click', 'ad123', 'campaign_xyz', 'Google Ads')
[2024-04-01T09:10:03.906+0000] {subprocess.py:93} INFO - Inserted data into ClickHouse: ('2024-03-25 08:30:00', 12345, 'click', 'ad123', 'campaign_xyz', 'Google Ads')
[2024-04-01T09:10:03.906+0000] {subprocess.py:93} INFO - Inserted data into ClickHouse: ('2024-03-25 09:15:00', 54321, 'view', 'ad456', 'campaign_abc', 'Facebook Ads')
[2024-04-01T09:10:03.906+0000] {subprocess.py:93} INFO - Inserted data into ClickHouse: ('2024-03-25 10:00:00', 67890, 'click', 'ad789', 'campaign_def', 'Twitter Ads')
[2024-04-01T09:10:03.906+0000] {subprocess.py:93} INFO - Inserted data into ClickHouse: ('2024-03-25 10:30:00', 23456, 'click', 'ad234', 'campaign_xyz', 'Google Ads')
[2024-04-01T09:10:03.906+0000] {subprocess.py:93} INFO - Inserted data into ClickHouse: ('2024-03-25 11:45:00', 67890, 'view', 'ad789', 'campaign_def', 'Twitter Ads')
[2024-04-01T09:10:03.906+0000] {subprocess.py:93} INFO - Inserted data into ClickHouse: ('2024-03-25 12:15:00', 12345, 'click', 'ad123', 'campaign_xyz', 'Google Ads')
[2024-04-01T09:10:03.906+0000] {subprocess.py:93} INFO - Inserted data into ClickHouse: ('2024-03-25 13:00:00', 54321, 'view', 'ad456', 'campaign_abc', 'Facebook Ads')
[2024-04-01T09:10:03.906+0000] {subprocess.py:93} INFO - Inserted data into ClickHouse: ('2024-03-25 14:30:00', 23456, 'click', 'ad234', 'campaign_xyz', 'Google Ads')
[2024-04-01T09:10:03.907+0000] {subprocess.py:93} INFO - Inserted data into ClickHouse: ('2024-03-25 15:45:00', 67890, 'view', 'ad789', 'campaign_def', 'Twitter Ads')
[2024-04-01T09:10:03.907+0000] {subprocess.py:93} INFO - Inserted data into ClickHouse: ('2024-03-25 16:15:00', 12345, 'click', 'ad123', 'campaign_xyz', 'Google Ads')
[2024-04-01T09:10:03.907+0000] {subprocess.py:93} INFO - done
[2024-04-01T09:10:03.907+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-04-01T09:10:03.907+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/clickhouse/consumer.py", line 99, in <module>
[2024-04-01T09:10:03.907+0000] {subprocess.py:93} INFO -     main()
[2024-04-01T09:10:03.907+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/clickhouse/consumer.py", line 88, in main
[2024-04-01T09:10:03.907+0000] {subprocess.py:93} INFO -     clickhouse_client.execute(insert_query2)
[2024-04-01T09:10:03.907+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 370, in execute
[2024-04-01T09:10:03.907+0000] {subprocess.py:93} INFO -     with self.disconnect_on_error(query, settings):
[2024-04-01T09:10:03.908+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
[2024-04-01T09:10:03.908+0000] {subprocess.py:93} INFO -     return next(self.gen)
[2024-04-01T09:10:03.908+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 314, in disconnect_on_error
[2024-04-01T09:10:03.908+0000] {subprocess.py:93} INFO -     self.establish_connection(settings)
[2024-04-01T09:10:03.908+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 301, in establish_connection
[2024-04-01T09:10:03.908+0000] {subprocess.py:93} INFO -     self.connection.force_connect()
[2024-04-01T09:10:03.908+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 258, in force_connect
[2024-04-01T09:10:03.908+0000] {subprocess.py:93} INFO -     self.connect()
[2024-04-01T09:10:03.908+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 417, in connect
[2024-04-01T09:10:03.908+0000] {subprocess.py:93} INFO -     raise err
[2024-04-01T09:10:03.908+0000] {subprocess.py:93} INFO - clickhouse_driver.errors.NetworkError: Code: 210. Connection refused (172.18.0.1:9000)
[2024-04-01T09:10:03.926+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-01T09:10:03.939+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-01T09:10:03.941+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=deploy_project_kafkaClickhouse, task_id=task_Clickhouse_Consumer, execution_date=20240330T093000, start_date=20240401T083848, end_date=20240401T091003
[2024-04-01T09:10:03.952+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 51 for task task_Clickhouse_Consumer (Bash command failed. The command returned a non-zero exit code 1.; 1288)
[2024-04-01T09:10:03.989+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-04-01T09:10:04.001+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
